dbt_cemist:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: 'dbt_cemist.duckdb'
      threads: 2
      extensions:
        - parquet
      external_root: "/home/matinnu/phd/projects/data_management_cemist/Soil Community"
